export const IssuesActions = {
    ISSUES_LOAD_REQUEST: 'issues/LOAD_REQUEST',
    ISSUES_LOAD_FAILURE: 'issues/LOAD_FAILURE',
    ISSUES_LOAD_SUCCESS: 'issues/LOAD_SUCCESS',
    ISSUE_TITLES_LOAD_REQUEST: 'issues/TITLES_LOAD_REQUEST',
    ISSUE_TITLES_LOAD_FAILURE: 'issues/TITLES_LOAD_FAILURE',
    ISSUE_TITLES_LOAD_SUCCESS: 'issues/TITLES_LOAD_SUCCESS',
}
